spring:
  application:
    name: eureka-service-db
server:
  port: 1112
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true